### ISSUE TITLE
Code from blog post is missing?

### ISSUE THREAD

**Issue by siddharth-krishna** [dusty-phillips/fast-bare-rescript-react#1]
Thanks for a really nice [blog post](https://dusty.phillips.codes/2021/09/30/fast-bare-rescript-react/) on setting up a fast rescript-react project! The blog post links to this repository, but I can't see any of the code from the post in here -- did you forget to push?

**Comment by dusty-phillips** [comment]
Eep. 😳 I think I did. And through a comedy of errors involving hard drive insanity, I don't have it anymore. I'll put a new one together; thanks for pointing it out!

**Comment by dusty-phillips** [comment]
This repo now has the code from the blog article. As a bonus, I've also made some minor updates to the article to accommodate some minor changes in both Rescript and Vite in the past several months: https://dusty.phillips.codes/2022/05/07/fast-bare-rescript-react-2022/

**Comment by siddharth-krishna** [comment]
Thank you, this is super helpful! (Sorry to hear about the HDD...)
